# C:\Users\Sujal\Downloads\Project Management Assistant Functional Features Overview\app\models.py
"""
Models Module for Project Management Assistant

This module defines all the Pydantic models used throughout the application.
Pydantic models provide data validation, serialization, and type hints.

Key Concepts:
- BaseModel: Pydantic's base class for creating data models
- Field: Used to add validation rules and metadata to model fields
- MongoBaseModel: Custom base class for all MongoDB documents
- *Base models: Used for creating new documents (POST requests)
- *Update models: Used for updating existing documents (PUT requests)
- Full models: Include all fields plus MongoDB metadata like _id, created_at, etc.
"""

from typing import List, Optional, Annotated
from datetime import datetime
from pydantic import BaseModel, Field, EmailStr, BeforeValidator
from bson import ObjectId

# ============================================================================
# MONGODB OBJECTID HANDLING
# ============================================================================
# MongoDB uses ObjectId as its primary key (_id), but it's not JSON serializable.
# We need to convert ObjectId to string for API responses.

def validate_object_id(v):
    """
    Custom validator function for MongoDB ObjectId.
    
    This function handles the conversion between MongoDB's ObjectId and Python strings:
    - If value is already an ObjectId, convert it to string for JSON serialization
    - If value is a string, keep it as is (it will be converted back to ObjectId when saving)
    - If value is neither, raise an error
    
    Args:
        v: The value to validate (can be ObjectId or string)
        
    Returns:
        str: String representation of the ObjectId
        
    Raises:
        ValueError: If the value cannot be converted to a valid ObjectId
    """
    if isinstance(v, ObjectId):
        return str(v)  # Convert ObjectId to string for API responses
    if isinstance(v, str):
        return v  # Already a string, return as-is
    raise ValueError("Invalid ObjectId")

# Custom type annotation for MongoDB ObjectId fields
# This tells Pydantic to run validate_object_id before validating the field
PyObjectId = Annotated[str, BeforeValidator(validate_object_id)]

# ============================================================================
# BASE MODEL FOR ALL MONGODB DOCUMENTS
# ============================================================================

class MongoBaseModel(BaseModel):
    """
    Base model for all MongoDB documents.
    
    This class serves as the parent for all models that will be stored in MongoDB.
    It handles the MongoDB _id field and provides common configuration.
    
    Attributes:
        id: MongoDB's ObjectId field, aliased as _id in the database
            - Optional because it's auto-generated by MongoDB on insert
            - Uses PyObjectId type for automatic conversion between ObjectId and string
    """
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    # Field(alias="_id") means: in MongoDB it's stored as "_id", in Python we access it as "id"
    # default=None means this field is optional (MongoDB will generate it)

    class Config:
        """
        Pydantic model configuration.
        
        These settings control how Pydantic handles this model:
        """
        populate_by_name = True  # Allow using both "id" and "_id" when creating instances
        arbitrary_types_allowed = True  # Allow custom types like ObjectId
        json_encoders = {ObjectId: str}  # Convert ObjectId to string in JSON responses

# ============================================================================
# MEMBER MANAGEMENT MODELS
# ============================================================================
# These models handle team member data (developers, designers, managers, etc.)

class MemberBase(BaseModel):
    """
    Base model for creating a new team member.
    
    This model contains only the fields that a user needs to provide when
    creating a new member. System fields like created_at are not included here.
    
    Attributes:
        name: Full name of the team member (must be at least 1 character)
        email: Email address (automatically validated by EmailStr)
        role: Job role (e.g., "Developer", "Designer", "Manager")
        skills: List of technical skills (e.g., ["Python", "React", "AWS"])
        experience_years: Years of professional experience (must be >= 0)
        availability_percent: Percentage of time available for work (0-100)
    """
    name: str = Field(..., min_length=1)
    # ... means this field is required
    # min_length=1 ensures the name is not empty
    
    email: EmailStr
    # EmailStr is a special Pydantic type that validates email format
    
    role: str
    # Job role/position (no validation, accepts any string)
    
    skills: List[str] = Field(default_factory=list)
    # default_factory=list creates an empty list if no skills are provided
    # This is better than default=[] which can cause mutation issues
    
    experience_years: int = Field(default=0, ge=0)
    # ge=0 means "greater than or equal to 0" (no negative experience)
    
    availability_percent: int = Field(default=100, ge=0, le=100)
    # ge=0, le=100 restricts values to 0-100 range

class Member(MongoBaseModel, MemberBase):
    """
    Complete member model including MongoDB metadata.
    
    This model is used for database operations and API responses.
    It inherits all fields from MemberBase and adds system-generated fields.
    
    Multiple inheritance:
    - MongoBaseModel: Provides the 'id' field and MongoDB configuration
    - MemberBase: Provides all the member-specific fields
    
    Additional Fields:
        created_at: Timestamp when the member was added to the system
        updated_at: Timestamp of the last update
    """
    created_at: datetime = Field(default_factory=datetime.utcnow)
    # default_factory=datetime.utcnow generates current time when creating new member
    # Note: utcnow() is called without parentheses - we pass the function itself
    
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    # This should ideally be updated on every modification

class MemberUpdate(BaseModel):
    """
    Model for updating an existing member.
    
    All fields are Optional, allowing partial updates.
    Only the fields provided in the request will be updated.
    
    Example: To update only the role, send: {"role": "Senior Developer"}
    The name, email, skills, etc. will remain unchanged.
    """
    name: Optional[str] = None
    email: Optional[EmailStr] = None
    role: Optional[str] = None
    skills: Optional[List[str]] = None
    experience_years: Optional[int] = Field(None, ge=0)
    availability_percent: Optional[int] = Field(None, ge=0, le=100)
    # All fields are Optional[Type] = None, meaning they can be omitted

# ============================================================================
# PROJECT MANAGEMENT MODELS
# ============================================================================
# These models handle project data, timelines, and milestones

class Milestone(BaseModel):
    """
    Represents a project milestone (a significant event or deliverable).
    
    Milestones help track project progress and important deadlines.
    
    Attributes:
        name: Description of the milestone (e.g., "Alpha Release", "User Testing")
        due_date: When this milestone should be completed
        completed: Whether this milestone has been achieved
    """
    name: str
    due_date: datetime
    completed: bool = False  # Defaults to False when creating new milestone

class ProjectBase(BaseModel):
    """
    Base model for creating a new project.
    
    A project is a collection of related tasks with a common goal.
    
    Attributes:
        name: Project name (required, at least 1 character)
        description: Detailed description of the project (optional)
        status: Current state of the project (e.g., "Not Started", "In Progress", "Completed")
        milestones: List of project milestones/deliverables
        deadline: Final deadline for the entire project (optional)
        team_member_ids: List of member IDs assigned to this project
    """
    name: str = Field(..., min_length=1)
    
    description: Optional[str] = None
    # Optional field for additional project details
    
    status: str = Field(default="Not Started")
    # Default status when creating a new project
    
    milestones: List[Milestone] = Field(default_factory=list)
    # List of milestone objects (starts empty)
    
    deadline: Optional[datetime] = None
    # Project deadline (optional because some projects are ongoing)
    
    team_member_ids: List[PyObjectId] = Field(alias="team_members", default_factory=list)
    # List of member IDs (stored as ObjectIds in MongoDB)
    # alias="team_members" means in API requests you can use "team_members"

class Project(MongoBaseModel, ProjectBase):
    """
    Complete project model with MongoDB metadata.
    
    Used for database storage and API responses.
    """
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class ProjectUpdate(BaseModel):
    """
    Model for updating an existing project.
    
    All fields are optional for partial updates.
    """
    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    milestones: Optional[List[Milestone]] = None
    deadline: Optional[datetime] = None
    team_member_ids: Optional[List[PyObjectId]] = Field(alias="team_members", default=None)

# ============================================================================
# TASK MANAGEMENT MODELS
# ============================================================================
# These models handle individual tasks within projects

class TaskBase(BaseModel):
    """
    Base model for creating a new task.
    
    A task is a specific piece of work that needs to be completed.
    Tasks belong to projects and can be assigned to team members.
    
    Attributes:
        project_id: ID of the parent project (required - every task must belong to a project)
        name: Task name/title (required, at least 1 character)
        description: Detailed description of what needs to be done (optional)
        status: Current state ("To Do", "In Progress", "Done")
        priority: Importance level ("Low", "Medium", "High")
        estimated_duration_hours: How long this task is expected to take (must be > 0)
        assigned_to_ids: List of member IDs assigned to work on this task
        dependency_ids: List of task IDs that must be completed before this task
        due_date: When this task should be completed (optional)
    """
    project_id: PyObjectId
    # Required field - every task must belong to a project
    
    name: str = Field(..., min_length=1)
    # Task title (required, non-empty)
    
    description: Optional[str] = None
    # Detailed task description (optional)
    
    status: str = Field(default="To Do")
    # Default status for new tasks
    # Common values: "To Do", "In Progress", "Done"
    
    priority: str = Field(default="Medium")
    # Default priority level
    # Common values: "Low", "Medium", "High"
    
    estimated_duration_hours: float = Field(..., gt=0)
    # gt=0 means "greater than 0" (positive number required)
    # This is used for time tracking and workload calculations
    
    assigned_to_ids: List[PyObjectId] = Field(alias="assigned_to", default_factory=list)
    # List of member IDs assigned to this task
    # alias="assigned_to" allows using "assigned_to" in API requests
    
    dependency_ids: List[PyObjectId] = Field(alias="dependencies", default_factory=list)
    # List of task IDs that must be completed before this one
    # Used for task ordering and scheduling
    
    due_date: Optional[datetime] = None
    # Optional specific deadline for this task

class Task(MongoBaseModel, TaskBase):
    """
    Complete task model with MongoDB metadata.
    
    Used for database storage and API responses.
    """
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

class TaskUpdate(BaseModel):
    """
    Model for updating an existing task.
    
    All fields are optional to allow partial updates.
    Commonly used when:
    - Changing task status ("To Do" -> "In Progress")
    - Reassigning tasks to different members
    - Updating estimates based on actual progress
    """
    name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    priority: Optional[str] = None
    estimated_duration_hours: Optional[float] = Field(None, gt=0)
    assigned_to_ids: Optional[List[PyObjectId]] = Field(alias="assigned_to", default=None)
    dependency_ids: Optional[List[PyObjectId]] = Field(alias="dependencies", default=None)
    due_date: Optional[datetime] = None

# ============================================================================
# TIME LOG MODELS
# ============================================================================
# These models track actual time spent working on tasks

class TimeLogBase(BaseModel):
    """
    Base model for creating a new time log entry.
    
    Time logs record actual work done on tasks. They're used for:
    - Tracking billable hours
    - Comparing actual vs. estimated time
    - Identifying tasks that take longer than expected
    - Generating timesheets and reports
    
    Attributes:
        task_id: ID of the task that was worked on (required)
        member_id: ID of the team member who did the work (required)
        hours_spent: Number of hours worked (must be > 0, can be decimal like 1.5)
        date_logged: When the work was done (defaults to current time)
        notes: Optional description of the work done
    """
    task_id: PyObjectId
    # Required - must specify which task this time is for
    
    member_id: PyObjectId
    # Required - must specify who did the work
    
    hours_spent: float = Field(..., gt=0)
    # gt=0 means hours must be positive
    # Can be decimal (e.g., 1.5 hours = 1 hour 30 minutes)
    
    date_logged: datetime = Field(default_factory=datetime.utcnow)
    # Defaults to current time when the log is created
    # Can be manually set to log work from a previous date
    
    notes: Optional[str] = None
    # Optional description of what was accomplished
    # e.g., "Fixed bug in login system" or "Implemented user dashboard"

class TimeLog(MongoBaseModel, TimeLogBase):
    """
    Complete time log model with MongoDB metadata.
    
    Used for database storage and API responses.
    Includes created_at for audit purposes (when the log entry was recorded).
    """
    created_at: datetime = Field(default_factory=datetime.utcnow)
    # When this log entry was created in the system
    # Note: This is different from date_logged which is when the work was done

class TimeLogUpdate(BaseModel):
    """
    Model for updating an existing time log entry.
    
    All fields are optional to allow partial updates.
    
    Common use cases:
    - Correcting hours_spent if entered incorrectly
    - Moving a log entry to a different task (changing task_id)
    - Reassigning a log to a different member (changing member_id)
    - Updating the date if logged on the wrong day
    - Adding or editing notes
    
    Note: task_id and member_id are included here to allow corrections,
    but they should be changed carefully as they affect reporting.
    """
    task_id: Optional[PyObjectId] = None
    # Allow changing which task this time is logged to
    
    member_id: Optional[PyObjectId] = None
    # Allow changing who the time is logged for
    
    hours_spent: Optional[float] = Field(None, gt=0)
    # Allow updating the number of hours
    
    date_logged: Optional[datetime] = None
    # Allow changing the date the work was done
    
    notes: Optional[str] = None
    # Allow updating the work description

# ============================================================================
# MODEL USAGE SUMMARY
# ============================================================================
"""
How these models are used in the API:

1. Creating new documents (POST requests):
   - Use *Base models (MemberBase, ProjectBase, TaskBase, TimeLogBase)
   - Example: POST /members/ with MemberBase data creates a new member

2. Retrieving documents (GET requests):
   - Return full models (Member, Project, Task, TimeLog)
   - Example: GET /members/123 returns a Member object with all fields

3. Updating documents (PUT requests):
   - Use *Update models (MemberUpdate, ProjectUpdate, TaskUpdate, TimeLogUpdate)
   - Example: PUT /tasks/456 with TaskUpdate data updates only specified fields

4. Database operations:
   - Full models are used for serialization/deserialization
   - MongoBaseModel handles ObjectId conversions automatically

Data flow example:
1. User sends POST /tasks/ with TaskBase JSON
2. FastAPI validates data against TaskBase model
3. Database class converts to Task model and saves to MongoDB
4. MongoDB auto-generates _id field
5. Database retrieves the new document
6. Task model serializes it (converts ObjectId to string)
7. API returns Task JSON to user
"""